# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.3'

    - name: Build
      run: |
        cd cmd/webproxy/
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o webproxy-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Test
      run: go test -v ./...

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: webproxy-${{ matrix.goos }}-${{ matrix.goarch }}
        path: webproxy-${{ matrix.goos }}-${{ matrix.goarch }}